version: '2'
services:
    microf-app:
        image: microf
        external_links:
            - microf-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry:8761/config
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
    microf-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: microf-cassandra
    microf-cassandra-node:
        image: cassandra:3.9
        links:
            - microf-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    microf-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: microf-cassandra-migration
        links:
            - microf-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
